// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using server.Services.UserServices.Data;

#nullable disable

namespace server.Database.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20231010070348_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("server.Services.UserServices.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfirmPassword")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConfirmPassword = "username1Password!",
                            Email = "username1@mail.com",
                            Password = "username1Password!",
                            Username = "username1",
                            Uuid = new Guid("c8e68271-3d93-4c44-a782-4927bd83c026")
                        },
                        new
                        {
                            Id = 2,
                            ConfirmPassword = "username2Password!",
                            Email = "username2@mail.com",
                            Password = "username2Password!",
                            Username = "username2",
                            Uuid = new Guid("1796b518-c738-4141-8bb2-9358dd79858e")
                        },
                        new
                        {
                            Id = 3,
                            ConfirmPassword = "username3Password!",
                            Email = "username3@mail.com",
                            Password = "username3Password!",
                            Username = "username3",
                            Uuid = new Guid("44b85378-4bbe-4bcf-b7af-2502d2ad4ae5")
                        },
                        new
                        {
                            Id = 4,
                            ConfirmPassword = "username4Password!",
                            Email = "username4@mail.com",
                            Password = "username4Password!",
                            Username = "username4",
                            Uuid = new Guid("540be087-d6a7-49bb-9d5b-f7743d904e85")
                        },
                        new
                        {
                            Id = 5,
                            ConfirmPassword = "username5Password!",
                            Email = "username5@mail.com",
                            Password = "username5Password!",
                            Username = "username5",
                            Uuid = new Guid("7c6ada17-8bda-422e-9ce0-6654f157905d")
                        },
                        new
                        {
                            Id = 6,
                            ConfirmPassword = "username6Password!",
                            Email = "username6@mail.com",
                            Password = "username6Password!",
                            Username = "username6",
                            Uuid = new Guid("0d7c863b-6c6e-46d7-a246-7289dd2b6559")
                        },
                        new
                        {
                            Id = 7,
                            ConfirmPassword = "username7Password!",
                            Email = "username7@mail.com",
                            Password = "username7Password!",
                            Username = "username7",
                            Uuid = new Guid("b8081fc8-272e-4d61-903a-544c6e3512ff")
                        },
                        new
                        {
                            Id = 8,
                            ConfirmPassword = "username8Password!",
                            Email = "username8@mail.com",
                            Password = "username8Password!",
                            Username = "username8",
                            Uuid = new Guid("80bad392-14b1-4a3c-9524-4555cbb5a7c3")
                        },
                        new
                        {
                            Id = 9,
                            ConfirmPassword = "username9Password!",
                            Email = "username9@mail.com",
                            Password = "username9Password!",
                            Username = "username9",
                            Uuid = new Guid("7dadea58-c77c-4c9a-80d6-3bbaa9fa02cd")
                        },
                        new
                        {
                            Id = 10,
                            ConfirmPassword = "username10Password!",
                            Email = "username10@mail.com",
                            Password = "username10Password!",
                            Username = "username10",
                            Uuid = new Guid("f4c6fdf4-39fc-42d5-b630-57fe3cbe6505")
                        },
                        new
                        {
                            Id = 11,
                            ConfirmPassword = "username11Password!",
                            Email = "username11@mail.com",
                            Password = "username11Password!",
                            Username = "username11",
                            Uuid = new Guid("7525ef9e-b7c0-4fa0-8c5a-3376fba24fe6")
                        },
                        new
                        {
                            Id = 12,
                            ConfirmPassword = "username12Password!",
                            Email = "username12@mail.com",
                            Password = "username12Password!",
                            Username = "username12",
                            Uuid = new Guid("eba3e990-42fb-4e07-a596-6550110ad3a9")
                        },
                        new
                        {
                            Id = 13,
                            ConfirmPassword = "username13Password!",
                            Email = "username13@mail.com",
                            Password = "username13Password!",
                            Username = "username13",
                            Uuid = new Guid("48511a77-c5fa-4ecd-bf0e-be09ffed3a38")
                        },
                        new
                        {
                            Id = 14,
                            ConfirmPassword = "username14Password!",
                            Email = "username14@mail.com",
                            Password = "username14Password!",
                            Username = "username14",
                            Uuid = new Guid("2b639f55-404f-4e17-b176-668d9847f0c4")
                        },
                        new
                        {
                            Id = 15,
                            ConfirmPassword = "username15Password!",
                            Email = "username15@mail.com",
                            Password = "username15Password!",
                            Username = "username15",
                            Uuid = new Guid("3934460e-4729-4f17-9b9b-62229947fe62")
                        },
                        new
                        {
                            Id = 16,
                            ConfirmPassword = "username16Password!",
                            Email = "username16@mail.com",
                            Password = "username16Password!",
                            Username = "username16",
                            Uuid = new Guid("7f165323-faf5-4a3c-a6b7-ec37ecb8d7d9")
                        },
                        new
                        {
                            Id = 17,
                            ConfirmPassword = "username17Password!",
                            Email = "username17@mail.com",
                            Password = "username17Password!",
                            Username = "username17",
                            Uuid = new Guid("294a2ff1-3fee-4ee8-beb6-a0bd3ae8b3fc")
                        },
                        new
                        {
                            Id = 18,
                            ConfirmPassword = "username18Password!",
                            Email = "username18@mail.com",
                            Password = "username18Password!",
                            Username = "username18",
                            Uuid = new Guid("c0a03ae8-9f38-41a5-8702-e093aa763d72")
                        },
                        new
                        {
                            Id = 19,
                            ConfirmPassword = "username19Password!",
                            Email = "username19@mail.com",
                            Password = "username19Password!",
                            Username = "username19",
                            Uuid = new Guid("7999bfbf-7ebd-4372-a4e8-9dad1d311594")
                        },
                        new
                        {
                            Id = 20,
                            ConfirmPassword = "username20Password!",
                            Email = "username20@mail.com",
                            Password = "username20Password!",
                            Username = "username20",
                            Uuid = new Guid("02191fec-004d-4dbd-8445-b90d4b87633f")
                        },
                        new
                        {
                            Id = 21,
                            ConfirmPassword = "username21Password!",
                            Email = "username21@mail.com",
                            Password = "username21Password!",
                            Username = "username21",
                            Uuid = new Guid("4e2ce9de-ee66-4d27-bb5b-82e2b5c99a7e")
                        },
                        new
                        {
                            Id = 22,
                            ConfirmPassword = "username22Password!",
                            Email = "username22@mail.com",
                            Password = "username22Password!",
                            Username = "username22",
                            Uuid = new Guid("269ee745-69de-4489-840d-4ff6fde4ea50")
                        },
                        new
                        {
                            Id = 23,
                            ConfirmPassword = "username23Password!",
                            Email = "username23@mail.com",
                            Password = "username23Password!",
                            Username = "username23",
                            Uuid = new Guid("3e0fd718-aa6e-4e8e-9282-fe57da89a4eb")
                        },
                        new
                        {
                            Id = 24,
                            ConfirmPassword = "username24Password!",
                            Email = "username24@mail.com",
                            Password = "username24Password!",
                            Username = "username24",
                            Uuid = new Guid("44fb6993-1ea0-473c-883b-d0ce33068047")
                        },
                        new
                        {
                            Id = 25,
                            ConfirmPassword = "username25Password!",
                            Email = "username25@mail.com",
                            Password = "username25Password!",
                            Username = "username25",
                            Uuid = new Guid("43684cf7-d65f-4f9f-8000-321eb7b2f5fd")
                        },
                        new
                        {
                            Id = 26,
                            ConfirmPassword = "username26Password!",
                            Email = "username26@mail.com",
                            Password = "username26Password!",
                            Username = "username26",
                            Uuid = new Guid("7af01e90-db13-427e-9f72-50b871050149")
                        },
                        new
                        {
                            Id = 27,
                            ConfirmPassword = "username27Password!",
                            Email = "username27@mail.com",
                            Password = "username27Password!",
                            Username = "username27",
                            Uuid = new Guid("4bbc0525-f08c-4783-a022-98d9dbc0e75e")
                        },
                        new
                        {
                            Id = 28,
                            ConfirmPassword = "username28Password!",
                            Email = "username28@mail.com",
                            Password = "username28Password!",
                            Username = "username28",
                            Uuid = new Guid("ba888d88-b19d-4e3c-bf04-1f385cf40e47")
                        },
                        new
                        {
                            Id = 29,
                            ConfirmPassword = "username29Password!",
                            Email = "username29@mail.com",
                            Password = "username29Password!",
                            Username = "username29",
                            Uuid = new Guid("1ba06e50-8778-4a66-a842-c4d8948c0956")
                        },
                        new
                        {
                            Id = 30,
                            ConfirmPassword = "username30Password!",
                            Email = "username30@mail.com",
                            Password = "username30Password!",
                            Username = "username30",
                            Uuid = new Guid("0e37c606-9ba2-4046-a5f8-a6c915d1098c")
                        },
                        new
                        {
                            Id = 31,
                            ConfirmPassword = "username31Password!",
                            Email = "username31@mail.com",
                            Password = "username31Password!",
                            Username = "username31",
                            Uuid = new Guid("3258b1db-71ab-4809-a1b0-4280ca59d5db")
                        },
                        new
                        {
                            Id = 32,
                            ConfirmPassword = "username32Password!",
                            Email = "username32@mail.com",
                            Password = "username32Password!",
                            Username = "username32",
                            Uuid = new Guid("306a1085-1bd8-49fa-8d30-4a3bd060f2bc")
                        },
                        new
                        {
                            Id = 33,
                            ConfirmPassword = "username33Password!",
                            Email = "username33@mail.com",
                            Password = "username33Password!",
                            Username = "username33",
                            Uuid = new Guid("e92a0b23-d3b4-45f4-948e-c71408eb7940")
                        },
                        new
                        {
                            Id = 34,
                            ConfirmPassword = "username34Password!",
                            Email = "username34@mail.com",
                            Password = "username34Password!",
                            Username = "username34",
                            Uuid = new Guid("7cf4fa8e-422a-49eb-9f1a-88fc4e7386df")
                        },
                        new
                        {
                            Id = 35,
                            ConfirmPassword = "username35Password!",
                            Email = "username35@mail.com",
                            Password = "username35Password!",
                            Username = "username35",
                            Uuid = new Guid("9c97dcf4-bd9d-4b11-8d1c-eed4d72c6889")
                        },
                        new
                        {
                            Id = 36,
                            ConfirmPassword = "username36Password!",
                            Email = "username36@mail.com",
                            Password = "username36Password!",
                            Username = "username36",
                            Uuid = new Guid("d0d37a40-7103-4065-a197-2fe7df363ac6")
                        },
                        new
                        {
                            Id = 37,
                            ConfirmPassword = "username37Password!",
                            Email = "username37@mail.com",
                            Password = "username37Password!",
                            Username = "username37",
                            Uuid = new Guid("b542f8f7-0c54-42d5-810d-621750e9babf")
                        },
                        new
                        {
                            Id = 38,
                            ConfirmPassword = "username38Password!",
                            Email = "username38@mail.com",
                            Password = "username38Password!",
                            Username = "username38",
                            Uuid = new Guid("544dbbf5-1551-43ae-8266-1f80ea57f125")
                        },
                        new
                        {
                            Id = 39,
                            ConfirmPassword = "username39Password!",
                            Email = "username39@mail.com",
                            Password = "username39Password!",
                            Username = "username39",
                            Uuid = new Guid("81f91fe0-486e-4b47-9a89-8052b8145aaf")
                        },
                        new
                        {
                            Id = 40,
                            ConfirmPassword = "username40Password!",
                            Email = "username40@mail.com",
                            Password = "username40Password!",
                            Username = "username40",
                            Uuid = new Guid("a90d7946-6343-476d-a889-d1467f52bd46")
                        },
                        new
                        {
                            Id = 41,
                            ConfirmPassword = "username41Password!",
                            Email = "username41@mail.com",
                            Password = "username41Password!",
                            Username = "username41",
                            Uuid = new Guid("d8c249dd-68d5-43f5-ba50-780e837f15ac")
                        },
                        new
                        {
                            Id = 42,
                            ConfirmPassword = "username42Password!",
                            Email = "username42@mail.com",
                            Password = "username42Password!",
                            Username = "username42",
                            Uuid = new Guid("dfaebe91-8974-455c-a5da-02eea6f6cb30")
                        },
                        new
                        {
                            Id = 43,
                            ConfirmPassword = "username43Password!",
                            Email = "username43@mail.com",
                            Password = "username43Password!",
                            Username = "username43",
                            Uuid = new Guid("382eeb7e-4b5a-472a-ae13-e9521807bb9a")
                        },
                        new
                        {
                            Id = 44,
                            ConfirmPassword = "username44Password!",
                            Email = "username44@mail.com",
                            Password = "username44Password!",
                            Username = "username44",
                            Uuid = new Guid("332d5788-e121-438a-8074-a0c1ab550db9")
                        },
                        new
                        {
                            Id = 45,
                            ConfirmPassword = "username45Password!",
                            Email = "username45@mail.com",
                            Password = "username45Password!",
                            Username = "username45",
                            Uuid = new Guid("d4cfa7cf-7775-4888-b0ec-2a27370c5642")
                        },
                        new
                        {
                            Id = 46,
                            ConfirmPassword = "username46Password!",
                            Email = "username46@mail.com",
                            Password = "username46Password!",
                            Username = "username46",
                            Uuid = new Guid("8b20e872-bd4c-4b73-b053-1940c1fbe8b5")
                        },
                        new
                        {
                            Id = 47,
                            ConfirmPassword = "username47Password!",
                            Email = "username47@mail.com",
                            Password = "username47Password!",
                            Username = "username47",
                            Uuid = new Guid("079ad9dd-17a3-4557-a0c2-e4d1a6035869")
                        },
                        new
                        {
                            Id = 48,
                            ConfirmPassword = "username48Password!",
                            Email = "username48@mail.com",
                            Password = "username48Password!",
                            Username = "username48",
                            Uuid = new Guid("be86d2ca-d3ff-4624-a98a-0f0f0022a619")
                        },
                        new
                        {
                            Id = 49,
                            ConfirmPassword = "username49Password!",
                            Email = "username49@mail.com",
                            Password = "username49Password!",
                            Username = "username49",
                            Uuid = new Guid("8be6970b-6b08-4cf8-8338-3ff9b1282e66")
                        },
                        new
                        {
                            Id = 50,
                            ConfirmPassword = "username50Password!",
                            Email = "username50@mail.com",
                            Password = "username50Password!",
                            Username = "username50",
                            Uuid = new Guid("8d7f5b4e-271c-43d5-af88-d44deb9600fd")
                        },
                        new
                        {
                            Id = 51,
                            ConfirmPassword = "username51Password!",
                            Email = "username51@mail.com",
                            Password = "username51Password!",
                            Username = "username51",
                            Uuid = new Guid("c4dc8c94-3253-4666-9133-cfa92f4541f6")
                        },
                        new
                        {
                            Id = 52,
                            ConfirmPassword = "username52Password!",
                            Email = "username52@mail.com",
                            Password = "username52Password!",
                            Username = "username52",
                            Uuid = new Guid("9ec44e30-1100-405d-9ab9-ce5106014fea")
                        },
                        new
                        {
                            Id = 53,
                            ConfirmPassword = "username53Password!",
                            Email = "username53@mail.com",
                            Password = "username53Password!",
                            Username = "username53",
                            Uuid = new Guid("3354a557-d89b-428e-962a-df2e7bc004b4")
                        },
                        new
                        {
                            Id = 54,
                            ConfirmPassword = "username54Password!",
                            Email = "username54@mail.com",
                            Password = "username54Password!",
                            Username = "username54",
                            Uuid = new Guid("07c17e45-21ec-4aa4-930c-f79db79b7609")
                        },
                        new
                        {
                            Id = 55,
                            ConfirmPassword = "username55Password!",
                            Email = "username55@mail.com",
                            Password = "username55Password!",
                            Username = "username55",
                            Uuid = new Guid("51cc3d8f-396f-4c8f-9b66-99d1ee033c7b")
                        },
                        new
                        {
                            Id = 56,
                            ConfirmPassword = "username56Password!",
                            Email = "username56@mail.com",
                            Password = "username56Password!",
                            Username = "username56",
                            Uuid = new Guid("c6644684-69f8-4a03-9987-717a0b2cf6e2")
                        },
                        new
                        {
                            Id = 57,
                            ConfirmPassword = "username57Password!",
                            Email = "username57@mail.com",
                            Password = "username57Password!",
                            Username = "username57",
                            Uuid = new Guid("e76c6e60-f446-468d-bc9a-3832102682b8")
                        },
                        new
                        {
                            Id = 58,
                            ConfirmPassword = "username58Password!",
                            Email = "username58@mail.com",
                            Password = "username58Password!",
                            Username = "username58",
                            Uuid = new Guid("142ac41e-f3ca-45d4-a86c-5e5f7a07ff2d")
                        },
                        new
                        {
                            Id = 59,
                            ConfirmPassword = "username59Password!",
                            Email = "username59@mail.com",
                            Password = "username59Password!",
                            Username = "username59",
                            Uuid = new Guid("d2a60247-8fbf-42ad-ac7d-2d632ea5505a")
                        },
                        new
                        {
                            Id = 60,
                            ConfirmPassword = "username60Password!",
                            Email = "username60@mail.com",
                            Password = "username60Password!",
                            Username = "username60",
                            Uuid = new Guid("bd62bb4f-5294-4eda-882b-d477f2bf981f")
                        },
                        new
                        {
                            Id = 61,
                            ConfirmPassword = "username61Password!",
                            Email = "username61@mail.com",
                            Password = "username61Password!",
                            Username = "username61",
                            Uuid = new Guid("ef7a317d-0d86-409e-93f1-b983e7183fd8")
                        },
                        new
                        {
                            Id = 62,
                            ConfirmPassword = "username62Password!",
                            Email = "username62@mail.com",
                            Password = "username62Password!",
                            Username = "username62",
                            Uuid = new Guid("52487453-dbfc-4768-8aea-2439f9f84a5a")
                        },
                        new
                        {
                            Id = 63,
                            ConfirmPassword = "username63Password!",
                            Email = "username63@mail.com",
                            Password = "username63Password!",
                            Username = "username63",
                            Uuid = new Guid("8faa29e8-a0f1-44c9-8a21-aa12ac6a7f88")
                        },
                        new
                        {
                            Id = 64,
                            ConfirmPassword = "username64Password!",
                            Email = "username64@mail.com",
                            Password = "username64Password!",
                            Username = "username64",
                            Uuid = new Guid("f9db8d64-6e4c-4444-a9c3-98b024e1c62b")
                        },
                        new
                        {
                            Id = 65,
                            ConfirmPassword = "username65Password!",
                            Email = "username65@mail.com",
                            Password = "username65Password!",
                            Username = "username65",
                            Uuid = new Guid("4adcc301-1e47-4cc9-b7f9-49ee82fb23f7")
                        },
                        new
                        {
                            Id = 66,
                            ConfirmPassword = "username66Password!",
                            Email = "username66@mail.com",
                            Password = "username66Password!",
                            Username = "username66",
                            Uuid = new Guid("bfdd9f8f-f9f5-48fd-ac80-0fbea931e913")
                        },
                        new
                        {
                            Id = 67,
                            ConfirmPassword = "username67Password!",
                            Email = "username67@mail.com",
                            Password = "username67Password!",
                            Username = "username67",
                            Uuid = new Guid("c55603a7-0f36-484d-aefc-17c2ba9f5e55")
                        },
                        new
                        {
                            Id = 68,
                            ConfirmPassword = "username68Password!",
                            Email = "username68@mail.com",
                            Password = "username68Password!",
                            Username = "username68",
                            Uuid = new Guid("5b2e53bf-884e-407c-8481-757e72d003f8")
                        },
                        new
                        {
                            Id = 69,
                            ConfirmPassword = "username69Password!",
                            Email = "username69@mail.com",
                            Password = "username69Password!",
                            Username = "username69",
                            Uuid = new Guid("8d824bf4-c1e6-4035-b786-5874cbb80dc1")
                        },
                        new
                        {
                            Id = 70,
                            ConfirmPassword = "username70Password!",
                            Email = "username70@mail.com",
                            Password = "username70Password!",
                            Username = "username70",
                            Uuid = new Guid("12cc6c5f-b84d-4524-8e49-f287a5877e59")
                        },
                        new
                        {
                            Id = 71,
                            ConfirmPassword = "username71Password!",
                            Email = "username71@mail.com",
                            Password = "username71Password!",
                            Username = "username71",
                            Uuid = new Guid("823557c9-9e9c-40e3-95ff-189c10f461e8")
                        },
                        new
                        {
                            Id = 72,
                            ConfirmPassword = "username72Password!",
                            Email = "username72@mail.com",
                            Password = "username72Password!",
                            Username = "username72",
                            Uuid = new Guid("60799f86-0ba4-4f5c-83bc-81a8e0cc88f0")
                        },
                        new
                        {
                            Id = 73,
                            ConfirmPassword = "username73Password!",
                            Email = "username73@mail.com",
                            Password = "username73Password!",
                            Username = "username73",
                            Uuid = new Guid("0e8b36ba-3554-4512-bc8c-65f3b086d33d")
                        },
                        new
                        {
                            Id = 74,
                            ConfirmPassword = "username74Password!",
                            Email = "username74@mail.com",
                            Password = "username74Password!",
                            Username = "username74",
                            Uuid = new Guid("2fd9c350-0658-4172-ac51-d873308c6104")
                        },
                        new
                        {
                            Id = 75,
                            ConfirmPassword = "username75Password!",
                            Email = "username75@mail.com",
                            Password = "username75Password!",
                            Username = "username75",
                            Uuid = new Guid("209eec98-f0bd-44dc-a184-80fd86626024")
                        },
                        new
                        {
                            Id = 76,
                            ConfirmPassword = "username76Password!",
                            Email = "username76@mail.com",
                            Password = "username76Password!",
                            Username = "username76",
                            Uuid = new Guid("1dad7e75-a5ae-431b-bf9e-25b3787dea6c")
                        },
                        new
                        {
                            Id = 77,
                            ConfirmPassword = "username77Password!",
                            Email = "username77@mail.com",
                            Password = "username77Password!",
                            Username = "username77",
                            Uuid = new Guid("1bc7fc97-c540-45c1-b67f-bba1a960f98e")
                        },
                        new
                        {
                            Id = 78,
                            ConfirmPassword = "username78Password!",
                            Email = "username78@mail.com",
                            Password = "username78Password!",
                            Username = "username78",
                            Uuid = new Guid("38ccd564-93cf-4683-acbd-58368dc6c439")
                        },
                        new
                        {
                            Id = 79,
                            ConfirmPassword = "username79Password!",
                            Email = "username79@mail.com",
                            Password = "username79Password!",
                            Username = "username79",
                            Uuid = new Guid("0237bd0c-d79b-4be0-a993-e5f121eda5fa")
                        },
                        new
                        {
                            Id = 80,
                            ConfirmPassword = "username80Password!",
                            Email = "username80@mail.com",
                            Password = "username80Password!",
                            Username = "username80",
                            Uuid = new Guid("de6db950-e04f-4f56-8c36-f6e5c36f02da")
                        },
                        new
                        {
                            Id = 81,
                            ConfirmPassword = "username81Password!",
                            Email = "username81@mail.com",
                            Password = "username81Password!",
                            Username = "username81",
                            Uuid = new Guid("1ad68046-a9c7-41fa-83df-53ba15c0e6cc")
                        },
                        new
                        {
                            Id = 82,
                            ConfirmPassword = "username82Password!",
                            Email = "username82@mail.com",
                            Password = "username82Password!",
                            Username = "username82",
                            Uuid = new Guid("f394f059-8e86-4962-96be-d816f07d0034")
                        },
                        new
                        {
                            Id = 83,
                            ConfirmPassword = "username83Password!",
                            Email = "username83@mail.com",
                            Password = "username83Password!",
                            Username = "username83",
                            Uuid = new Guid("129c13eb-cbce-49cf-94c1-6350cde7c9a2")
                        },
                        new
                        {
                            Id = 84,
                            ConfirmPassword = "username84Password!",
                            Email = "username84@mail.com",
                            Password = "username84Password!",
                            Username = "username84",
                            Uuid = new Guid("7c923ba8-1ef4-49fa-821c-c4a64b89adb7")
                        },
                        new
                        {
                            Id = 85,
                            ConfirmPassword = "username85Password!",
                            Email = "username85@mail.com",
                            Password = "username85Password!",
                            Username = "username85",
                            Uuid = new Guid("a32e3b1b-92a3-4bc8-b5bb-963d4aac6ef4")
                        },
                        new
                        {
                            Id = 86,
                            ConfirmPassword = "username86Password!",
                            Email = "username86@mail.com",
                            Password = "username86Password!",
                            Username = "username86",
                            Uuid = new Guid("1c23a52f-8b24-4ac1-9480-c6be765cb941")
                        },
                        new
                        {
                            Id = 87,
                            ConfirmPassword = "username87Password!",
                            Email = "username87@mail.com",
                            Password = "username87Password!",
                            Username = "username87",
                            Uuid = new Guid("87667112-7b06-4a0a-a850-0fe817282c1f")
                        },
                        new
                        {
                            Id = 88,
                            ConfirmPassword = "username88Password!",
                            Email = "username88@mail.com",
                            Password = "username88Password!",
                            Username = "username88",
                            Uuid = new Guid("7353fd7c-43f0-491f-91e5-1a90c3eb7ec9")
                        },
                        new
                        {
                            Id = 89,
                            ConfirmPassword = "username89Password!",
                            Email = "username89@mail.com",
                            Password = "username89Password!",
                            Username = "username89",
                            Uuid = new Guid("bafa47f3-2d27-47d8-94d3-e75e9b2c178c")
                        },
                        new
                        {
                            Id = 90,
                            ConfirmPassword = "username90Password!",
                            Email = "username90@mail.com",
                            Password = "username90Password!",
                            Username = "username90",
                            Uuid = new Guid("a985d6ab-88f2-417f-bc0d-9b4c64178800")
                        },
                        new
                        {
                            Id = 91,
                            ConfirmPassword = "username91Password!",
                            Email = "username91@mail.com",
                            Password = "username91Password!",
                            Username = "username91",
                            Uuid = new Guid("cd6e8100-c821-48d2-a637-e1ed8a8a3f22")
                        },
                        new
                        {
                            Id = 92,
                            ConfirmPassword = "username92Password!",
                            Email = "username92@mail.com",
                            Password = "username92Password!",
                            Username = "username92",
                            Uuid = new Guid("4cc59e8a-1672-49a9-8ada-00337bdaaaa8")
                        },
                        new
                        {
                            Id = 93,
                            ConfirmPassword = "username93Password!",
                            Email = "username93@mail.com",
                            Password = "username93Password!",
                            Username = "username93",
                            Uuid = new Guid("07e30477-42d6-4e32-a8b5-91ff80014710")
                        },
                        new
                        {
                            Id = 94,
                            ConfirmPassword = "username94Password!",
                            Email = "username94@mail.com",
                            Password = "username94Password!",
                            Username = "username94",
                            Uuid = new Guid("7f6cb152-0f9b-40db-a900-0f924ccb5caa")
                        },
                        new
                        {
                            Id = 95,
                            ConfirmPassword = "username95Password!",
                            Email = "username95@mail.com",
                            Password = "username95Password!",
                            Username = "username95",
                            Uuid = new Guid("8383f0cf-f1cf-40c1-aab4-49f011bc35e7")
                        },
                        new
                        {
                            Id = 96,
                            ConfirmPassword = "username96Password!",
                            Email = "username96@mail.com",
                            Password = "username96Password!",
                            Username = "username96",
                            Uuid = new Guid("92b0e13a-9da8-4ef5-be25-54f0987afd94")
                        },
                        new
                        {
                            Id = 97,
                            ConfirmPassword = "username97Password!",
                            Email = "username97@mail.com",
                            Password = "username97Password!",
                            Username = "username97",
                            Uuid = new Guid("0a18e7f4-4841-4b32-bfca-48c7aa247403")
                        },
                        new
                        {
                            Id = 98,
                            ConfirmPassword = "username98Password!",
                            Email = "username98@mail.com",
                            Password = "username98Password!",
                            Username = "username98",
                            Uuid = new Guid("af82d65d-5af7-4e36-b367-161cf5f92b9f")
                        },
                        new
                        {
                            Id = 99,
                            ConfirmPassword = "username99Password!",
                            Email = "username99@mail.com",
                            Password = "username99Password!",
                            Username = "username99",
                            Uuid = new Guid("4299a0c7-2793-4533-acbb-e4a866ae3397")
                        },
                        new
                        {
                            Id = 100,
                            ConfirmPassword = "username100Password!",
                            Email = "username100@mail.com",
                            Password = "username100Password!",
                            Username = "username100",
                            Uuid = new Guid("279507ee-738c-4d15-9f9c-ebe5145af68a")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
